language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1
  - nightly

notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
        - julia --color=yes -e 'include(joinpath("docs","make.jl"))'
      after_success: skip
