language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
env:
  - USE_MASTER=true
  - USE_MASTER=""

notifications:
  email: false
matrix:
  exclude:
    - julia: 1.0
      env: USE_MASTER=true
    - julia: 1.1
      env: USE_MASTER=true
    - julia: nightly
      env: USE_MASTER=""
  allow_failures:
  - julia: nightly

before_script:
  - if [ ! -z "$USE_MASTER" ]; then curl $SCRIPT_URL -o install_master.jl; julia install_master.jl;  fi

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      env: USE_MASTER=""
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using ImageNoise; ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs","make.jl"))'
      after_success: skip
